# All values are metric, angles are in radians
plan:
  -
    action: 'wait'
    duration: 5
  -
    action: 'cam'
    duration: 5
    target: -83
  -
    action: 'takeoff'
    duration: 3
  -
    action: 'slam'
    duration: 0.5
    target: 1
  -
    action: 'setpoint'
    duration: 0.1
    target:
      px: 0.0
      py: 0.0
      pz: 1.0
      yaw: 0.0
  -
    action: 'ctrl'
    duration: 5
    target: true
  -
    action: 'setpoint'
    duration: 10
    target:
      px: 3.0
      py: 0.0
      pz: 1.0
      yaw: 0.0
  -
    action: 'setpoint'
    duration: 10
    target:
      px: 3.0
      py: 3.0
      pz: 1.0
      yaw: 0.0
  -
    action: 'setpoint'
    duration: 10
    target:
      px: 0.0
      py: 3.0
      pz: 1.0
      yaw: 0.0
  -
    action: 'setpoint'
    duration: 10
    target:
      px: 0.0
      py: 0.0
      pz: 1.0
      yaw: 0.0
  -
    action: 'ctrl'
    duration: 0.5
    target: false
  -
    action: 'slam'
    duration: 0.5
    target: 0
  -
    action: 'land'
    duration: 1
